repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Run Ruff Check
        entry: uv run ruff check --fix
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-format
        name: Run Ruff Format
        entry: uv run ruff format
        language: system
        pass_filenames: false
        always_run: true

      - id: ty-check
        name: Run Ty Check
        entry: uv run ty check
        language: system
        pass_filenames: false
        always_run: true

      - id: pyright
        name: Run Pyright
        entry: uv run pyright
        language: system
        pass_filenames: false
        always_run: true

      - id: interrogate
        name: Run Interrogate
        entry: uv run interrogate
        language: system
        pass_filenames: false
        always_run: true

      - id: tally
        name: Run Tally
        entry: uv run tally lint --fix Dockerfile
        language: system
        pass_filenames: false
        always_run: true

      - id: taplo
        name: Run Taplo
        entry: uv run taplo fmt pyproject.toml
        language: system
        pass_filenames: false
        always_run: true

      - id: prettier
        name: Run Prettier
        entry: npx prettier --log-level warn --write .
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: Run Pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
