repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Run Ruff Check
        entry: uv run --locked ruff check --fix
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-format
        name: Run Ruff Format
        entry: uv run --locked ruff format
        language: system
        pass_filenames: false
        always_run: true

      - id: ty-check
        name: Run Ty Check
        entry: uv run --locked ty check
        language: system
        pass_filenames: false
        always_run: true

      - id: pyright
        name: Run Pyright
        entry: uv run --locked pyright
        language: system
        pass_filenames: false
        always_run: true

      - id: interrogate
        name: Run Interrogate
        entry: uv run --locked interrogate
        language: system
        pass_filenames: false
        always_run: true

      - id: tally
        name: Run Tally
        entry: uv run --locked tally lint --fix Dockerfile
        language: system
        pass_filenames: false
        always_run: true

      - id: prettier
        name: Run Prettier
        entry: npx --no-install prettier --write .
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: Run Pytest
        entry: uv run --locked pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
