name: CI

on:
  push: &ci_trigger
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/ci.yaml"
      - "pyproject.toml"
      - "uv.lock"
  pull_request: *ci_trigger

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-checks:
    runs-on: ubuntu-latest
    name: "Static Checks (Synced with Local Environment)"
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Install dependencies
        run: uv sync --locked --all-groups

      - name: Run Ruff
        run: uv run ruff check

      - name: Run Ruff Format
        run: uv run ruff format --check

      - name: Run Ty Check
        run: uv run ty check

      - name: Run Pyright
        run: uv run pyright

      - name: Run Interrogate
        run: uv run interrogate

      - name: Run Tally
        run: uv run tally lint Dockerfile

      - name: Run Taplo
        run: uv run taplo check pyproject.toml

      - name: Run Pytest
        run: uv run pytest
