name: Prettier

on:
  push: &ci_trigger
    branches:
      - main
    paths:
      - "**.yaml"
      - "**.yml"
      - "**.json"
      - "**.md"
      - "**.toml"
  pull_request: *ci_trigger

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    name: "Prettier Format Check"
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --check .
